// Auto-generated Audio Asset Map
// Populated by:  npm run audio   (scripts/generate_audio.js)
// Key   : the exact spoken text  (and "key:<narration key>" aliases)
// Value : path of the pre-generated MP3 in /public/assets/audio
export const audioMap = {
  "Ready to see how one amount can wear three costumes? Let's roll!": "/assets/audio/home_intro.mp3",
  "key:home_intro": "/assets/audio/home_intro.mp3",
  "Robo cuts a pizza into four equal slices and eats one slice. Alex says: That's one quarter of the pizza, zero point two five of the pizza, and twenty-five percent of the pizza. Those are three different amounts! Is that actually true?": "/assets/audio/wonder_prompt.mp3",
  "key:wonder_prompt": "/assets/audio/wonder_prompt.mp3",
  "What if Robo ate a second slice? Which numbers would change, and would they all change together?": "/assets/audio/wonder_teaser.mp3",
  "key:wonder_teaser": "/assets/audio/wonder_teaser.mp3",
  "Fractions, decimals and percents are three names for exactly the same amount!": "/assets/audio/wonder_rule.mp3",
  "key:wonder_rule": "/assets/audio/wonder_rule.mp3",
  "Fractions, decimals and percents are three ways to write the same part of a whole! Half a pizza can be written as the fraction one half, the decimal zero point five, or fifty percent. The word percent means out of one hundred, so fifty percent is fifty out of every one hundred!": "/assets/audio/story_slide_1.mp3",
  "key:story_slide_1": "/assets/audio/story_slide_1.mp3",
  "One amount, three costumes: a fraction, a decimal and a percent!": "/assets/audio/story_slide_1_key.mp3",
  "key:story_slide_1_key": "/assets/audio/story_slide_1_key.mp3",
  "Imagine a big grid made of one hundred tiny squares. Every single square is one percent, which is one hundredth, which is zero point zero one. Shade thirty-seven squares and you have shaded thirty-seven percent, which is thirty-seven over one hundred, which is zero point three seven. Percent always means out of one hundred!": "/assets/audio/story_slide_2.mp3",
  "key:story_slide_2": "/assets/audio/story_slide_2.mp3",
  "Percent means out of one hundred, so thirty-seven percent is thirty-seven over one hundred, or zero point three seven!": "/assets/audio/story_slide_2_key.mp3",
  "key:story_slide_2_key": "/assets/audio/story_slide_2_key.mp3",
  "Look around! A phone battery at seventy-five percent is three quarters full. A sale sign that says fifty percent off takes away one half of the price. A quiz score of eighteen out of twenty is ninety percent. Percents help us compare fairly, even when the wholes are different sizes!": "/assets/audio/story_slide_3.mp3",
  "key:story_slide_3": "/assets/audio/story_slide_3.mp3",
  "A battery at seventy-five percent is three quarters full, and three quarters is the same as zero point seven five!": "/assets/audio/story_slide_3_key.mp3",
  "key:story_slide_3_key": "/assets/audio/story_slide_3_key.mp3",
  "Detective time! Let's switch three fifths into its other costumes. Multiply the top and the bottom by twenty to get sixty over one hundred. That means sixty percent, and as a decimal it is zero point six. To go back, write the percent over one hundred and simplify!": "/assets/audio/story_slide_4.mp3",
  "key:story_slide_4": "/assets/audio/story_slide_4.mp3",
  "Make the denominator one hundred, and the numerator is the percent!": "/assets/audio/story_slide_4_key.mp3",
  "key:story_slide_4_key": "/assets/audio/story_slide_4_key.mp3",
  "Welcome to the Percent Grid Lab! Tap or drag on the grid to shade squares. Watch the fraction, the decimal and the percent change together as you shade!": "/assets/audio/station_a_intro.mp3",
  "key:station_a_intro": "/assets/audio/station_a_intro.mp3",
  "Time for the Number Line Sorter! Drag each card onto the number line where it belongs. Change each fraction or decimal into a percent to find its spot, then press Check!": "/assets/audio/station_b_intro.mp3",
  "key:station_b_intro": "/assets/audio/station_b_intro.mp3",
  "Welcome, detective! Three of these four cards show exactly the same amount, but one imposter is hiding. Change the cards into the same costume to spot the imposter, then tap it!": "/assets/audio/station_c_intro.mp3",
  "key:station_c_intro": "/assets/audio/station_c_intro.mp3",
  "Welcome to the Real-World Percent Lab! Pick an object, then complete each mission by setting it to the amount shown. Fractions, decimals and percents are all fair game!": "/assets/audio/station_d_intro.mp3",
  "key:station_d_intro": "/assets/audio/station_d_intro.mp3",
  "You found one half! fifty out of one hundred squares is fifty percent, one half and zero point five. One amount in three costumes!": "/assets/audio/discover_half.mp3",
  "key:discover_half": "/assets/audio/discover_half.mp3",
  "You found one quarter! twenty-five out of one hundred squares is twenty-five percent, one quarter and zero point two five!": "/assets/audio/discover_quarter.mp3",
  "key:discover_quarter": "/assets/audio/discover_quarter.mp3",
  "Three quarters! seventy-five out of one hundred squares is seventy-five percent, three quarters and zero point seven five!": "/assets/audio/discover_threeq.mp3",
  "key:discover_threeq": "/assets/audio/discover_threeq.mp3",
  "One tenth! ten out of one hundred squares is ten percent, one tenth and zero point one!": "/assets/audio/discover_tenth.mp3",
  "key:discover_tenth": "/assets/audio/discover_tenth.mp3",
  "Amazing! You found all four landmarks. Percent is just a number out of one hundred!": "/assets/audio/discover_all.mp3",
  "key:discover_all": "/assets/audio/discover_all.mp3",
  "Perfect! Every card is on the right spot. Changing to percents makes the number line easy!": "/assets/audio/sorter_round_correct.mp3",
  "key:sorter_round_correct": "/assets/audio/sorter_round_correct.mp3",
  "Some cards bounced back. Change each fraction or decimal into a percent, then try again!": "/assets/audio/sorter_some_wrong.mp3",
  "key:sorter_some_wrong": "/assets/audio/sorter_some_wrong.mp3",
  "All three rounds complete! You are a number line master!": "/assets/audio/sorter_all_rounds.mp3",
  "key:sorter_all_rounds": "/assets/audio/sorter_all_rounds.mp3",
  "Case closed! You caught the imposter. Great detective work!": "/assets/audio/detective_caught.mp3",
  "key:detective_caught": "/assets/audio/detective_caught.mp3",
  "Not the imposter! That card matches the others. Keep investigating!": "/assets/audio/detective_wrong.mp3",
  "key:detective_wrong": "/assets/audio/detective_wrong.mp3",
  "All the cases are solved! You are a top detective!": "/assets/audio/detective_all.mp3",
  "key:detective_all": "/assets/audio/detective_all.mp3",
  "Mission complete! You matched the amount exactly!": "/assets/audio/mission_complete.mp3",
  "key:mission_complete": "/assets/audio/mission_complete.mp3",
  "All the missions for this object are done! Try another one!": "/assets/audio/mission_all.mp3",
  "key:mission_all": "/assets/audio/mission_all.mp3",
  "Charge the battery to three quarters.": "/assets/audio/mission_battery_1.mp3",
  "key:mission_battery_1": "/assets/audio/mission_battery_1.mp3",
  "Set the battery to zero point two. That is a low battery!": "/assets/audio/mission_battery_2.mp3",
  "key:mission_battery_2": "/assets/audio/mission_battery_2.mp3",
  "Make the battery show ninety percent.": "/assets/audio/mission_battery_3.mp3",
  "key:mission_battery_3": "/assets/audio/mission_battery_3.mp3",
  "Fill the bottle to zero point five.": "/assets/audio/mission_bottle_1.mp3",
  "key:mission_bottle_1": "/assets/audio/mission_bottle_1.mp3",
  "Fill the bottle to one fifth.": "/assets/audio/mission_bottle_2.mp3",
  "key:mission_bottle_2": "/assets/audio/mission_bottle_2.mp3",
  "Fill the bottle to seventy percent.": "/assets/audio/mission_bottle_3.mp3",
  "key:mission_bottle_3": "/assets/audio/mission_bottle_3.mp3",
  "Get three fifths of the class to vote for pizza.": "/assets/audio/mission_vote_1.mp3",
  "key:mission_vote_1": "/assets/audio/mission_vote_1.mp3",
  "Get zero point four of the class to vote for pizza.": "/assets/audio/mission_vote_2.mp3",
  "key:mission_vote_2": "/assets/audio/mission_vote_2.mp3",
  "Get eighty percent of the class to vote for pizza.": "/assets/audio/mission_vote_3.mp3",
  "key:mission_vote_3": "/assets/audio/mission_vote_3.mp3",
  "Score four fifths of the marks on the test.": "/assets/audio/mission_score_1.mp3",
  "key:mission_score_1": "/assets/audio/mission_score_1.mp3",
  "Show a test score of zero point six.": "/assets/audio/mission_score_2.mp3",
  "key:mission_score_2": "/assets/audio/mission_score_2.mp3",
  "Score full marks: one hundred percent!": "/assets/audio/mission_score_3.mp3",
  "key:mission_score_3": "/assets/audio/mission_score_3.mp3",
  "Choose your world on the map! Beat each world to unlock the next. Earn stars and XP!": "/assets/audio/practice_welcome.mp3",
  "key:practice_welcome": "/assets/audio/practice_welcome.mp3",
  "Awesome job! You got it right!": "/assets/audio/correct_cheer.mp3",
  "key:correct_cheer": "/assets/audio/correct_cheer.mp3",
  "Not quite. Remember, percent means out of one hundred!": "/assets/audio/incorrect_try_again.mp3",
  "key:incorrect_try_again": "/assets/audio/incorrect_try_again.mp3",
  "No worries! Let's practice some more. Try again to master this world!": "/assets/audio/out_of_hearts.mp3",
  "key:out_of_hearts": "/assets/audio/out_of_hearts.mp3",
  "Congratulations! You completed the world and earned new stars!": "/assets/audio/world_complete.mp3",
  "key:world_complete": "/assets/audio/world_complete.mp3",
  "The hundred grid has thirty-seven shaded squares. What percent of the grid is shaded?": "/assets/audio/w1_q1_prompt.mp3",
  "key:w1_q1_prompt": "/assets/audio/w1_q1_prompt.mp3",
  "The grid has one hundred squares in all. The number of shaded squares out of one hundred is the percent.": "/assets/audio/w1_q1_hint.mp3",
  "key:w1_q1_hint": "/assets/audio/w1_q1_hint.mp3",
  "Only eight squares on the hundred grid are shaded. What percent is shaded?": "/assets/audio/w1_q2_prompt.mp3",
  "key:w1_q2_prompt": "/assets/audio/w1_q2_prompt.mp3",
  "Count the shaded squares. It is eight out of one hundred.": "/assets/audio/w1_q2_hint.mp3",
  "key:w1_q2_hint": "/assets/audio/w1_q2_hint.mp3",
  "The word percent means out of how many?": "/assets/audio/w1_q3_prompt.mp3",
  "key:w1_q3_prompt": "/assets/audio/w1_q3_prompt.mp3",
  "Think of a hundred grid. How many squares make the whole?": "/assets/audio/w1_q3_hint.mp3",
  "key:w1_q3_hint": "/assets/audio/w1_q3_hint.mp3",
  "sixty-four squares are shaded on a hundred grid. What percent is NOT shaded?": "/assets/audio/w1_q4_prompt.mp3",
  "key:w1_q4_prompt": "/assets/audio/w1_q4_prompt.mp3",
  "The whole grid is one hundred percent. Subtract the shaded part from one hundred.": "/assets/audio/w1_q4_hint.mp3",
  "key:w1_q4_hint": "/assets/audio/w1_q4_hint.mp3",
  "Exactly twenty-five squares are shaded on a hundred grid. What percent is shaded?": "/assets/audio/w1_q5_prompt.mp3",
  "key:w1_q5_prompt": "/assets/audio/w1_q5_prompt.mp3",
  "Count the shaded squares out of one hundred.": "/assets/audio/w1_q5_hint.mp3",
  "key:w1_q5_hint": "/assets/audio/w1_q5_hint.mp3",
  "One square on a hundred grid is what percent of the whole grid?": "/assets/audio/w1_q6_prompt.mp3",
  "key:w1_q6_prompt": "/assets/audio/w1_q6_prompt.mp3",
  "It is one out of one hundred squares.": "/assets/audio/w1_q6_hint.mp3",
  "key:w1_q6_hint": "/assets/audio/w1_q6_hint.mp3",
  "ninety squares are shaded on a hundred grid. What percent is shaded?": "/assets/audio/w1_q7_prompt.mp3",
  "key:w1_q7_prompt": "/assets/audio/w1_q7_prompt.mp3",
  "key:w1_q7_hint": "/assets/audio/w1_q5_hint.mp3",
  "sixty out of one hundred students like football. What percent of the students like football?": "/assets/audio/w1_q8_prompt.mp3",
  "key:w1_q8_prompt": "/assets/audio/w1_q8_prompt.mp3",
  "Percent means out of one hundred. The number out of one hundred is the percent.": "/assets/audio/w1_q8_hint.mp3",
  "key:w1_q8_hint": "/assets/audio/w1_q8_hint.mp3",
  "The whole hundred grid is shaded. What percent is that?": "/assets/audio/w1_q9_prompt.mp3",
  "key:w1_q9_prompt": "/assets/audio/w1_q9_prompt.mp3",
  "All one hundred squares out of one hundred squares.": "/assets/audio/w1_q9_hint.mp3",
  "key:w1_q9_hint": "/assets/audio/w1_q9_hint.mp3",
  "forty-five squares are shaded on a hundred grid. Which percent shows the shaded part?": "/assets/audio/w1_q10_prompt.mp3",
  "key:w1_q10_prompt": "/assets/audio/w1_q10_prompt.mp3",
  "key:w1_q10_hint": "/assets/audio/w1_q5_hint.mp3",
  "Write forty-seven percent as a fraction with denominator one hundred.": "/assets/audio/w2_q1_prompt.mp3",
  "key:w2_q1_prompt": "/assets/audio/w2_q1_prompt.mp3",
  "Percent means out of one hundred. Put the percent number over one hundred.": "/assets/audio/w2_q1_hint.mp3",
  "key:w2_q1_hint": "/assets/audio/w2_q1_hint.mp3",
  "Write nine percent as a fraction with denominator one hundred.": "/assets/audio/w2_q2_prompt.mp3",
  "key:w2_q2_prompt": "/assets/audio/w2_q2_prompt.mp3",
  "key:w2_q2_hint": "/assets/audio/w2_q1_hint.mp3",
  "Write sixty-three percent as a fraction with denominator one hundred.": "/assets/audio/w2_q3_prompt.mp3",
  "key:w2_q3_prompt": "/assets/audio/w2_q3_prompt.mp3",
  "key:w2_q3_hint": "/assets/audio/w2_q1_hint.mp3",
  "Write eighty-one percent as a fraction with denominator one hundred.": "/assets/audio/w2_q4_prompt.mp3",
  "key:w2_q4_prompt": "/assets/audio/w2_q4_prompt.mp3",
  "key:w2_q4_hint": "/assets/audio/w2_q1_hint.mp3",
  "Write twenty-three percent as a fraction with denominator one hundred.": "/assets/audio/w2_q5_prompt.mp3",
  "key:w2_q5_prompt": "/assets/audio/w2_q5_prompt.mp3",
  "key:w2_q5_hint": "/assets/audio/w2_q1_hint.mp3",
  "Which fraction is the same as five percent?": "/assets/audio/w2_q6_prompt.mp3",
  "key:w2_q6_prompt": "/assets/audio/w2_q6_prompt.mp3",
  "key:w2_q6_hint": "/assets/audio/w2_q1_hint.mp3",
  "Which fraction is the same as seventy-eight percent?": "/assets/audio/w2_q7_prompt.mp3",
  "key:w2_q7_prompt": "/assets/audio/w2_q7_prompt.mp3",
  "key:w2_q7_hint": "/assets/audio/w2_q1_hint.mp3",
  "Which fraction is the same as ninety-nine percent?": "/assets/audio/w2_q8_prompt.mp3",
  "key:w2_q8_prompt": "/assets/audio/w2_q8_prompt.mp3",
  "key:w2_q8_hint": "/assets/audio/w2_q1_hint.mp3",
  "Which fraction is the same as thirty-one percent?": "/assets/audio/w2_q9_prompt.mp3",
  "key:w2_q9_prompt": "/assets/audio/w2_q9_prompt.mp3",
  "key:w2_q9_hint": "/assets/audio/w2_q1_hint.mp3",
  "Which fraction is the same as sixteen percent?": "/assets/audio/w2_q10_prompt.mp3",
  "key:w2_q10_prompt": "/assets/audio/w2_q10_prompt.mp3",
  "key:w2_q10_hint": "/assets/audio/w2_q1_hint.mp3",
  "Write twenty-five percent as a fraction in simplest form.": "/assets/audio/w3_q1_prompt.mp3",
  "key:w3_q1_prompt": "/assets/audio/w3_q1_prompt.mp3",
  "Write twenty-five over one hundred first. Then divide the top and bottom by the same number until you can't any more.": "/assets/audio/w3_q1_hint.mp3",
  "key:w3_q1_hint": "/assets/audio/w3_q1_hint.mp3",
  "Write fifty percent as a fraction in simplest form.": "/assets/audio/w3_q2_prompt.mp3",
  "key:w3_q2_prompt": "/assets/audio/w3_q2_prompt.mp3",
  "Write fifty over one hundred first. Then divide the top and bottom by the same number until you can't any more.": "/assets/audio/w3_q2_hint.mp3",
  "key:w3_q2_hint": "/assets/audio/w3_q2_hint.mp3",
  "Write twenty percent as a fraction in simplest form.": "/assets/audio/w3_q3_prompt.mp3",
  "key:w3_q3_prompt": "/assets/audio/w3_q3_prompt.mp3",
  "Write twenty over one hundred first. Then divide the top and bottom by the same number until you can't any more.": "/assets/audio/w3_q3_hint.mp3",
  "key:w3_q3_hint": "/assets/audio/w3_q3_hint.mp3",
  "Write sixty percent as a fraction in simplest form.": "/assets/audio/w3_q4_prompt.mp3",
  "key:w3_q4_prompt": "/assets/audio/w3_q4_prompt.mp3",
  "Write sixty over one hundred first. Then divide the top and bottom by the same number until you can't any more.": "/assets/audio/w3_q4_hint.mp3",
  "key:w3_q4_hint": "/assets/audio/w3_q4_hint.mp3",
  "Write seventy-five percent as a fraction in simplest form.": "/assets/audio/w3_q5_prompt.mp3",
  "key:w3_q5_prompt": "/assets/audio/w3_q5_prompt.mp3",
  "Write seventy-five over one hundred first. Then divide the top and bottom by the same number until you can't any more.": "/assets/audio/w3_q5_hint.mp3",
  "key:w3_q5_hint": "/assets/audio/w3_q5_hint.mp3",
  "Write forty percent as a fraction in simplest form.": "/assets/audio/w3_q6_prompt.mp3",
  "key:w3_q6_prompt": "/assets/audio/w3_q6_prompt.mp3",
  "Write forty over one hundred first. Then divide the top and bottom by the same number until you can't any more.": "/assets/audio/w3_q6_hint.mp3",
  "key:w3_q6_hint": "/assets/audio/w3_q6_hint.mp3",
  "Write thirty-five percent as a fraction in simplest form.": "/assets/audio/w3_q7_prompt.mp3",
  "key:w3_q7_prompt": "/assets/audio/w3_q7_prompt.mp3",
  "Write thirty-five over one hundred first. Then divide the top and bottom by the same number until you can't any more.": "/assets/audio/w3_q7_hint.mp3",
  "key:w3_q7_hint": "/assets/audio/w3_q7_hint.mp3",
  "Write ninety percent as a fraction in simplest form.": "/assets/audio/w3_q8_prompt.mp3",
  "key:w3_q8_prompt": "/assets/audio/w3_q8_prompt.mp3",
  "Write ninety over one hundred first. Then divide the top and bottom by the same number until you can't any more.": "/assets/audio/w3_q8_hint.mp3",
  "key:w3_q8_hint": "/assets/audio/w3_q8_hint.mp3",
  "Write forty-five percent as a fraction in simplest form.": "/assets/audio/w3_q9_prompt.mp3",
  "key:w3_q9_prompt": "/assets/audio/w3_q9_prompt.mp3",
  "Write forty-five over one hundred first. Then divide the top and bottom by the same number until you can't any more.": "/assets/audio/w3_q9_hint.mp3",
  "key:w3_q9_hint": "/assets/audio/w3_q9_hint.mp3",
  "Write four percent as a fraction in simplest form.": "/assets/audio/w3_q10_prompt.mp3",
  "key:w3_q10_prompt": "/assets/audio/w3_q10_prompt.mp3",
  "Write four over one hundred first. Then divide the top and bottom by the same number until you can't any more.": "/assets/audio/w3_q10_hint.mp3",
  "key:w3_q10_hint": "/assets/audio/w3_q10_hint.mp3",
  "Write forty-five percent as a decimal.": "/assets/audio/w4_q1_prompt.mp3",
  "key:w4_q1_prompt": "/assets/audio/w4_q1_prompt.mp3",
  "Divide by one hundred. That slides the decimal point two places to the left.": "/assets/audio/w4_q1_hint.mp3",
  "key:w4_q1_hint": "/assets/audio/w4_q1_hint.mp3",
  "Write seven percent as a decimal.": "/assets/audio/w4_q2_prompt.mp3",
  "key:w4_q2_prompt": "/assets/audio/w4_q2_prompt.mp3",
  "key:w4_q2_hint": "/assets/audio/w4_q1_hint.mp3",
  "Write eighty percent as a decimal.": "/assets/audio/w4_q3_prompt.mp3",
  "key:w4_q3_prompt": "/assets/audio/w4_q3_prompt.mp3",
  "key:w4_q3_hint": "/assets/audio/w4_q1_hint.mp3",
  "Write sixty-two percent as a decimal.": "/assets/audio/w4_q4_prompt.mp3",
  "key:w4_q4_prompt": "/assets/audio/w4_q4_prompt.mp3",
  "key:w4_q4_hint": "/assets/audio/w4_q1_hint.mp3",
  "Write nine percent as a decimal.": "/assets/audio/w4_q5_prompt.mp3",
  "key:w4_q5_prompt": "/assets/audio/w4_q5_prompt.mp3",
  "key:w4_q5_hint": "/assets/audio/w4_q1_hint.mp3",
  "Write thirty percent as a decimal.": "/assets/audio/w4_q6_prompt.mp3",
  "key:w4_q6_prompt": "/assets/audio/w4_q6_prompt.mp3",
  "key:w4_q6_hint": "/assets/audio/w4_q1_hint.mp3",
  "Write ninety-nine percent as a decimal.": "/assets/audio/w4_q7_prompt.mp3",
  "key:w4_q7_prompt": "/assets/audio/w4_q7_prompt.mp3",
  "key:w4_q7_hint": "/assets/audio/w4_q1_hint.mp3",
  "Write twelve percent as a decimal.": "/assets/audio/w4_q8_prompt.mp3",
  "key:w4_q8_prompt": "/assets/audio/w4_q8_prompt.mp3",
  "key:w4_q8_hint": "/assets/audio/w4_q1_hint.mp3",
  "Write five percent as a decimal.": "/assets/audio/w4_q9_prompt.mp3",
  "key:w4_q9_prompt": "/assets/audio/w4_q9_prompt.mp3",
  "key:w4_q9_hint": "/assets/audio/w4_q1_hint.mp3",
  "Write one hundred percent as a decimal.": "/assets/audio/w4_q10_prompt.mp3",
  "key:w4_q10_prompt": "/assets/audio/w4_q10_prompt.mp3",
  "key:w4_q10_hint": "/assets/audio/w4_q1_hint.mp3",
  "Write zero point six as a percent.": "/assets/audio/w5_q1_prompt.mp3",
  "key:w5_q1_prompt": "/assets/audio/w5_q1_prompt.mp3",
  "Multiply by one hundred. That slides the decimal point two places to the right.": "/assets/audio/w5_q1_hint.mp3",
  "key:w5_q1_hint": "/assets/audio/w5_q1_hint.mp3",
  "Write zero point zero five as a percent.": "/assets/audio/w5_q2_prompt.mp3",
  "key:w5_q2_prompt": "/assets/audio/w5_q2_prompt.mp3",
  "key:w5_q2_hint": "/assets/audio/w5_q1_hint.mp3",
  "Write zero point three two as a percent.": "/assets/audio/w5_q3_prompt.mp3",
  "key:w5_q3_prompt": "/assets/audio/w5_q3_prompt.mp3",
  "key:w5_q3_hint": "/assets/audio/w5_q1_hint.mp3",
  "Write zero point nine as a percent.": "/assets/audio/w5_q4_prompt.mp3",
  "key:w5_q4_prompt": "/assets/audio/w5_q4_prompt.mp3",
  "key:w5_q4_hint": "/assets/audio/w5_q1_hint.mp3",
  "Write zero point zero seven as a percent.": "/assets/audio/w5_q5_prompt.mp3",
  "key:w5_q5_prompt": "/assets/audio/w5_q5_prompt.mp3",
  "key:w5_q5_hint": "/assets/audio/w5_q1_hint.mp3",
  "Write zero point seven five as a percent.": "/assets/audio/w5_q6_prompt.mp3",
  "key:w5_q6_prompt": "/assets/audio/w5_q6_prompt.mp3",
  "key:w5_q6_hint": "/assets/audio/w5_q1_hint.mp3",
  "Write zero point four as a percent.": "/assets/audio/w5_q7_prompt.mp3",
  "key:w5_q7_prompt": "/assets/audio/w5_q7_prompt.mp3",
  "key:w5_q7_hint": "/assets/audio/w5_q1_hint.mp3",
  "Write zero point one eight as a percent.": "/assets/audio/w5_q8_prompt.mp3",
  "key:w5_q8_prompt": "/assets/audio/w5_q8_prompt.mp3",
  "key:w5_q8_hint": "/assets/audio/w5_q1_hint.mp3",
  "Write zero point zero one as a percent.": "/assets/audio/w5_q9_prompt.mp3",
  "key:w5_q9_prompt": "/assets/audio/w5_q9_prompt.mp3",
  "key:w5_q9_hint": "/assets/audio/w5_q1_hint.mp3",
  "Write zero point five as a percent.": "/assets/audio/w5_q10_prompt.mp3",
  "key:w5_q10_prompt": "/assets/audio/w5_q10_prompt.mp3",
  "key:w5_q10_hint": "/assets/audio/w5_q1_hint.mp3",
  "Write one quarter as a percent.": "/assets/audio/w6_q1_prompt.mp3",
  "key:w6_q1_prompt": "/assets/audio/w6_q1_prompt.mp3",
  "Multiply the top and the bottom by twenty-five to make the denominator one hundred.": "/assets/audio/w6_q1_hint.mp3",
  "key:w6_q1_hint": "/assets/audio/w6_q1_hint.mp3",
  "Write three fifths as a percent.": "/assets/audio/w6_q2_prompt.mp3",
  "key:w6_q2_prompt": "/assets/audio/w6_q2_prompt.mp3",
  "Multiply the top and the bottom by twenty to make the denominator one hundred.": "/assets/audio/w6_q2_hint.mp3",
  "key:w6_q2_hint": "/assets/audio/w6_q2_hint.mp3",
  "Write seven tenths as a percent.": "/assets/audio/w6_q3_prompt.mp3",
  "key:w6_q3_prompt": "/assets/audio/w6_q3_prompt.mp3",
  "Multiply the top and the bottom by ten to make the denominator one hundred.": "/assets/audio/w6_q3_hint.mp3",
  "key:w6_q3_hint": "/assets/audio/w6_q3_hint.mp3",
  "Write nine over twenty as a percent.": "/assets/audio/w6_q4_prompt.mp3",
  "key:w6_q4_prompt": "/assets/audio/w6_q4_prompt.mp3",
  "Multiply the top and the bottom by five to make the denominator one hundred.": "/assets/audio/w6_q4_hint.mp3",
  "key:w6_q4_hint": "/assets/audio/w6_q4_hint.mp3",
  "Write three over twenty-five as a percent.": "/assets/audio/w6_q5_prompt.mp3",
  "key:w6_q5_prompt": "/assets/audio/w6_q5_prompt.mp3",
  "Multiply the top and the bottom by four to make the denominator one hundred.": "/assets/audio/w6_q5_hint.mp3",
  "key:w6_q5_hint": "/assets/audio/w6_q5_hint.mp3",
  "Write seventeen over fifty as a percent.": "/assets/audio/w6_q6_prompt.mp3",
  "key:w6_q6_prompt": "/assets/audio/w6_q6_prompt.mp3",
  "Multiply the top and the bottom by two to make the denominator one hundred.": "/assets/audio/w6_q6_hint.mp3",
  "key:w6_q6_hint": "/assets/audio/w6_q6_hint.mp3",
  "Write one half as a percent.": "/assets/audio/w6_q7_prompt.mp3",
  "key:w6_q7_prompt": "/assets/audio/w6_q7_prompt.mp3",
  "Multiply the top and the bottom by fifty to make the denominator one hundred.": "/assets/audio/w6_q7_hint.mp3",
  "key:w6_q7_hint": "/assets/audio/w6_q7_hint.mp3",
  "Write four fifths as a percent.": "/assets/audio/w6_q8_prompt.mp3",
  "key:w6_q8_prompt": "/assets/audio/w6_q8_prompt.mp3",
  "key:w6_q8_hint": "/assets/audio/w6_q2_hint.mp3",
  "Write thirteen over twenty as a percent.": "/assets/audio/w6_q9_prompt.mp3",
  "key:w6_q9_prompt": "/assets/audio/w6_q9_prompt.mp3",
  "key:w6_q9_hint": "/assets/audio/w6_q4_hint.mp3",
  "Write eleven over twenty-five as a percent.": "/assets/audio/w6_q10_prompt.mp3",
  "key:w6_q10_prompt": "/assets/audio/w6_q10_prompt.mp3",
  "key:w6_q10_hint": "/assets/audio/w6_q5_hint.mp3",
  "Which is equal to one half?": "/assets/audio/w7_q1_prompt.mp3",
  "key:w7_q1_prompt": "/assets/audio/w7_q1_prompt.mp3",
  "one half means one out of two. Half of one hundred is fifty, so one half is fifty percent, or zero point five.": "/assets/audio/w7_q1_hint.mp3",
  "key:w7_q1_hint": "/assets/audio/w7_q1_hint.mp3",
  "Which is equal to zero point two five?": "/assets/audio/w7_q2_prompt.mp3",
  "key:w7_q2_prompt": "/assets/audio/w7_q2_prompt.mp3",
  "zero point two five is twenty-five over one hundred. Divide the top and bottom by twenty-five.": "/assets/audio/w7_q2_hint.mp3",
  "key:w7_q2_hint": "/assets/audio/w7_q2_hint.mp3",
  "Which is equal to sixty percent?": "/assets/audio/w7_q3_prompt.mp3",
  "key:w7_q3_prompt": "/assets/audio/w7_q3_prompt.mp3",
  "sixty percent is sixty over one hundred. Divide the top and bottom by twenty.": "/assets/audio/w7_q3_hint.mp3",
  "key:w7_q3_hint": "/assets/audio/w7_q3_hint.mp3",
  "Which is equal to three quarters?": "/assets/audio/w7_q4_prompt.mp3",
  "key:w7_q4_prompt": "/assets/audio/w7_q4_prompt.mp3",
  "Make the denominator one hundred. Multiply the top and bottom by twenty-five.": "/assets/audio/w7_q4_hint.mp3",
  "key:w7_q4_hint": "/assets/audio/w7_q4_hint.mp3",
  "Which is equal to zero point two?": "/assets/audio/w7_q5_prompt.mp3",
  "key:w7_q5_prompt": "/assets/audio/w7_q5_prompt.mp3",
  "Multiply by one hundred. Slide the decimal point two places to the right.": "/assets/audio/w7_q5_hint.mp3",
  "key:w7_q5_hint": "/assets/audio/w7_q5_hint.mp3",
  "Which is equal to forty-five percent?": "/assets/audio/w7_q6_prompt.mp3",
  "key:w7_q6_prompt": "/assets/audio/w7_q6_prompt.mp3",
  "forty-five percent is forty-five over one hundred. Divide the top and bottom by five.": "/assets/audio/w7_q6_hint.mp3",
  "key:w7_q6_hint": "/assets/audio/w7_q6_hint.mp3",
  "Which is equal to zero point eight?": "/assets/audio/w7_q7_prompt.mp3",
  "key:w7_q7_prompt": "/assets/audio/w7_q7_prompt.mp3",
  "zero point eight is eight tenths. Divide the top and bottom by two.": "/assets/audio/w7_q7_hint.mp3",
  "key:w7_q7_hint": "/assets/audio/w7_q7_hint.mp3",
  "Which is equal to one fifth?": "/assets/audio/w7_q8_prompt.mp3",
  "key:w7_q8_prompt": "/assets/audio/w7_q8_prompt.mp3",
  "Multiply the top and bottom by twenty to get a denominator of one hundred.": "/assets/audio/w7_q8_hint.mp3",
  "key:w7_q8_hint": "/assets/audio/w7_q8_hint.mp3",
  "Which one is NOT equal to zero point four?": "/assets/audio/w7_q9_prompt.mp3",
  "key:w7_q9_prompt": "/assets/audio/w7_q9_prompt.mp3",
  "Change every choice into a decimal. Which one is not zero point four?": "/assets/audio/w7_q9_hint.mp3",
  "key:w7_q9_hint": "/assets/audio/w7_q9_hint.mp3",
  "Which is equal to three eighths?": "/assets/audio/w7_q10_prompt.mp3",
  "key:w7_q10_prompt": "/assets/audio/w7_q10_prompt.mp3",
  "Divide the top by the bottom: three divided by eight.": "/assets/audio/w7_q10_hint.mp3",
  "key:w7_q10_hint": "/assets/audio/w7_q10_hint.mp3",
  "Which number is the greatest?": "/assets/audio/w8_q1_prompt.mp3",
  "key:w8_q1_prompt": "/assets/audio/w8_q1_prompt.mp3",
  "Change every choice into a percent. Then compare the percents.": "/assets/audio/w8_q1_hint.mp3",
  "key:w8_q1_hint": "/assets/audio/w8_q1_hint.mp3",
  "Which number is the smallest?": "/assets/audio/w8_q2_prompt.mp3",
  "key:w8_q2_prompt": "/assets/audio/w8_q2_prompt.mp3",
  "key:w8_q2_hint": "/assets/audio/w8_q1_hint.mp3",
  "key:w8_q3_prompt": "/assets/audio/w8_q1_prompt.mp3",
  "key:w8_q3_hint": "/assets/audio/w8_q1_hint.mp3",
  "key:w8_q4_prompt": "/assets/audio/w8_q2_prompt.mp3",
  "key:w8_q4_hint": "/assets/audio/w8_q1_hint.mp3",
  "key:w8_q5_prompt": "/assets/audio/w8_q1_prompt.mp3",
  "key:w8_q5_hint": "/assets/audio/w8_q1_hint.mp3",
  "Which number is between forty percent and sixty percent?": "/assets/audio/w8_q6_prompt.mp3",
  "key:w8_q6_prompt": "/assets/audio/w8_q6_prompt.mp3",
  "key:w8_q6_hint": "/assets/audio/w8_q1_hint.mp3",
  "Which number is closest to one whole (one hundred percent)?": "/assets/audio/w8_q7_prompt.mp3",
  "key:w8_q7_prompt": "/assets/audio/w8_q7_prompt.mp3",
  "key:w8_q7_hint": "/assets/audio/w8_q1_hint.mp3",
  "Which number is greater than zero point six?": "/assets/audio/w8_q8_prompt.mp3",
  "key:w8_q8_prompt": "/assets/audio/w8_q8_prompt.mp3",
  "key:w8_q8_hint": "/assets/audio/w8_q1_hint.mp3",
  "Which number is less than one quarter?": "/assets/audio/w8_q9_prompt.mp3",
  "key:w8_q9_prompt": "/assets/audio/w8_q9_prompt.mp3",
  "key:w8_q9_hint": "/assets/audio/w8_q1_hint.mp3",
  "key:w8_q10_prompt": "/assets/audio/w8_q1_prompt.mp3",
  "key:w8_q10_hint": "/assets/audio/w8_q1_hint.mp3",
  "Write one hundred fifty percent as a decimal.": "/assets/audio/w9_q1_prompt.mp3",
  "key:w9_q1_prompt": "/assets/audio/w9_q1_prompt.mp3",
  "Divide by one hundred. More than one hundred percent means more than one whole.": "/assets/audio/w9_q1_hint.mp3",
  "key:w9_q1_hint": "/assets/audio/w9_q1_hint.mp3",
  "Write two hundred percent as a decimal.": "/assets/audio/w9_q2_prompt.mp3",
  "key:w9_q2_prompt": "/assets/audio/w9_q2_prompt.mp3",
  "one hundred percent is one whole. So two hundred percent is how many wholes?": "/assets/audio/w9_q2_hint.mp3",
  "key:w9_q2_hint": "/assets/audio/w9_q2_hint.mp3",
  "Write one hundred twenty-five percent as an improper fraction in simplest form.": "/assets/audio/w9_q3_prompt.mp3",
  "key:w9_q3_prompt": "/assets/audio/w9_q3_prompt.mp3",
  "Write one hundred twenty-five over one hundred and divide the top and bottom by twenty-five.": "/assets/audio/w9_q3_hint.mp3",
  "key:w9_q3_hint": "/assets/audio/w9_q3_hint.mp3",
  "Write zero point five percent as a decimal.": "/assets/audio/w9_q4_prompt.mp3",
  "key:w9_q4_prompt": "/assets/audio/w9_q4_prompt.mp3",
  "Divide zero point five by one hundred. Slide the decimal point two places to the left.": "/assets/audio/w9_q4_hint.mp3",
  "key:w9_q4_hint": "/assets/audio/w9_q4_hint.mp3",
  "Write two point five as a percent.": "/assets/audio/w9_q5_prompt.mp3",
  "key:w9_q5_prompt": "/assets/audio/w9_q5_prompt.mp3",
  "key:w9_q5_hint": "/assets/audio/w7_q5_hint.mp3",
  "Write three hundred percent as a decimal.": "/assets/audio/w9_q6_prompt.mp3",
  "key:w9_q6_prompt": "/assets/audio/w9_q6_prompt.mp3",
  "Every one hundred percent is one whole. How many wholes is three hundred percent?": "/assets/audio/w9_q6_hint.mp3",
  "key:w9_q6_hint": "/assets/audio/w9_q6_hint.mp3",
  "Write one point two as a percent.": "/assets/audio/w9_q7_prompt.mp3",
  "key:w9_q7_prompt": "/assets/audio/w9_q7_prompt.mp3",
  "key:w9_q7_hint": "/assets/audio/w7_q5_hint.mp3",
  "Write zero point two percent as a decimal.": "/assets/audio/w9_q8_prompt.mp3",
  "key:w9_q8_prompt": "/assets/audio/w9_q8_prompt.mp3",
  "Divide zero point two by one hundred. Slide the decimal point two places to the left.": "/assets/audio/w9_q8_hint.mp3",
  "key:w9_q8_hint": "/assets/audio/w9_q8_hint.mp3",
  "Write three halves as a percent.": "/assets/audio/w9_q9_prompt.mp3",
  "key:w9_q9_prompt": "/assets/audio/w9_q9_prompt.mp3",
  "Multiply the top and bottom by fifty to make the denominator one hundred.": "/assets/audio/w9_q9_hint.mp3",
  "key:w9_q9_hint": "/assets/audio/w9_q9_hint.mp3",
  "Write one hundred seventy-five percent as a mixed number in simplest form.": "/assets/audio/w9_q10_prompt.mp3",
  "key:w9_q10_prompt": "/assets/audio/w9_q10_prompt.mp3",
  "one hundred seventy-five percent is one hundred percent plus seventy-five percent. That is one whole and seventy-five over one hundred.": "/assets/audio/w9_q10_hint.mp3",
  "key:w9_q10_hint": "/assets/audio/w9_q10_hint.mp3",
  "There are forty students in a class. thirty of them walk to school. What percent of the students walk to school?": "/assets/audio/w10_q1_prompt.mp3",
  "key:w10_q1_prompt": "/assets/audio/w10_q1_prompt.mp3",
  "Write thirty over forty and simplify to three quarters. Then make the denominator one hundred.": "/assets/audio/w10_q1_hint.mp3",
  "key:w10_q1_hint": "/assets/audio/w10_q1_hint.mp3",
  "Mei scored eighteen out of twenty on a quiz. What is her score as a percent?": "/assets/audio/w10_q2_prompt.mp3",
  "key:w10_q2_prompt": "/assets/audio/w10_q2_prompt.mp3",
  "Multiply the top and bottom of eighteen over twenty by five to make the denominator one hundred.": "/assets/audio/w10_q2_hint.mp3",
  "key:w10_q2_hint": "/assets/audio/w10_q2_hint.mp3",
  "A phone battery is thirty-five percent charged. What fraction of the battery is charged? Give your answer in simplest form.": "/assets/audio/w10_q3_prompt.mp3",
  "key:w10_q3_prompt": "/assets/audio/w10_q3_prompt.mp3",
  "Write thirty-five over one hundred. Then divide the top and bottom by five.": "/assets/audio/w10_q3_hint.mp3",
  "key:w10_q3_hint": "/assets/audio/w10_q3_hint.mp3",
  "A jug is zero point seven five full of juice. What percent of the jug is full?": "/assets/audio/w10_q4_prompt.mp3",
  "key:w10_q4_prompt": "/assets/audio/w10_q4_prompt.mp3",
  "Multiply zero point seven five by one hundred. Slide the decimal point two places to the right.": "/assets/audio/w10_q4_hint.mp3",
  "key:w10_q4_hint": "/assets/audio/w10_q4_hint.mp3",
  "A bag has twenty-five marbles. seven of them are red. What percent of the marbles are red?": "/assets/audio/w10_q5_prompt.mp3",
  "key:w10_q5_prompt": "/assets/audio/w10_q5_prompt.mp3",
  "Write seven over twenty-five. Multiply the top and bottom by four to make the denominator one hundred.": "/assets/audio/w10_q5_hint.mp3",
  "key:w10_q5_hint": "/assets/audio/w10_q5_hint.mp3",
  "A shop takes twenty percent off the price of a bag. What fraction of the price is taken off? Give your answer in simplest form.": "/assets/audio/w10_q6_prompt.mp3",
  "key:w10_q6_prompt": "/assets/audio/w10_q6_prompt.mp3",
  "Write twenty over one hundred. Then divide the top and bottom by twenty.": "/assets/audio/w10_q6_hint.mp3",
  "key:w10_q6_hint": "/assets/audio/w10_q6_hint.mp3",
  "Rui has read zero point four of his book. What percent of the book is left to read?": "/assets/audio/w10_q7_prompt.mp3",
  "key:w10_q7_prompt": "/assets/audio/w10_q7_prompt.mp3",
  "First change zero point four into a percent. Then subtract it from one hundred percent.": "/assets/audio/w10_q7_hint.mp3",
  "key:w10_q7_hint": "/assets/audio/w10_q7_hint.mp3",
  "forty-five percent of the students in a club are boys. What fraction of the club are girls? Give your answer in simplest form.": "/assets/audio/w10_q8_prompt.mp3",
  "key:w10_q8_prompt": "/assets/audio/w10_q8_prompt.mp3",
  "Girls are one hundred percent minus forty-five percent. Then write the percent over one hundred and simplify.": "/assets/audio/w10_q8_hint.mp3",
  "key:w10_q8_hint": "/assets/audio/w10_q8_hint.mp3",
  "A tank is three eighths full of water. What percent of the tank is full?": "/assets/audio/w10_q9_prompt.mp3",
  "key:w10_q9_prompt": "/assets/audio/w10_q9_prompt.mp3",
  "Divide three by eight to get a decimal. Then multiply by one hundred.": "/assets/audio/w10_q9_hint.mp3",
  "key:w10_q9_hint": "/assets/audio/w10_q9_hint.mp3",
  "Aisha spent zero point three five of her savings. What percent of her savings did she NOT spend?": "/assets/audio/w10_q10_prompt.mp3",
  "key:w10_q10_prompt": "/assets/audio/w10_q10_prompt.mp3",
  "Change zero point three five into a percent. Then subtract from one hundred percent.": "/assets/audio/w10_q10_hint.mp3",
  "key:w10_q10_hint": "/assets/audio/w10_q10_hint.mp3",
  "Amazing work! Let's reflect on what you learned.": "/assets/audio/reflect_intro.mp3",
  "key:reflect_intro": "/assets/audio/reflect_intro.mp3",
  "What does the word percent mean?": "/assets/audio/reflect_q1.mp3",
  "key:reflect_q1": "/assets/audio/reflect_q1.mp3",
  "Percent means out of one hundred! So one percent is one out of one hundred, and fifty percent is fifty out of one hundred, which is exactly half.": "/assets/audio/reflect_a1.mp3",
  "key:reflect_a1": "/assets/audio/reflect_a1.mp3",
  "How do you change a percent into a fraction?": "/assets/audio/reflect_q2.mp3",
  "key:reflect_q2": "/assets/audio/reflect_q2.mp3",
  "Write the percent over one hundred, then simplify. For example, forty-five percent equals forty-five over one hundred equals nine over twenty.": "/assets/audio/reflect_a2.mp3",
  "key:reflect_a2": "/assets/audio/reflect_a2.mp3",
  "How do you change a percent into a decimal?": "/assets/audio/reflect_q3.mp3",
  "key:reflect_q3": "/assets/audio/reflect_q3.mp3",
  "Divide by one hundred, which slides the decimal point two places to the left. For example, forty-five percent equals zero point four five.": "/assets/audio/reflect_a3.mp3",
  "key:reflect_a3": "/assets/audio/reflect_a3.mp3",
  "How do you change a decimal into a percent?": "/assets/audio/reflect_q4.mp3",
  "key:reflect_q4": "/assets/audio/reflect_q4.mp3",
  "Multiply by one hundred, which slides the decimal point two places to the right. For example, zero point six equals sixty percent.": "/assets/audio/reflect_a4.mp3",
  "key:reflect_a4": "/assets/audio/reflect_a4.mp3",
  "How do you change a fraction into a percent?": "/assets/audio/reflect_q5.mp3",
  "key:reflect_q5": "/assets/audio/reflect_q5.mp3",
  "Make the denominator one hundred by multiplying the top and bottom by the same number. For example, three fifths equals sixty over one hundred equals sixty percent.": "/assets/audio/reflect_a5.mp3",
  "key:reflect_a5": "/assets/audio/reflect_a5.mp3",
  "Where can you see percentages in real life?": "/assets/audio/reflect_q6.mp3",
  "key:reflect_q6": "/assets/audio/reflect_q6.mp3",
  "On phone batteries, sale signs, test scores, sports stats and class surveys!": "/assets/audio/reflect_a6.mp3",
  "key:reflect_a6": "/assets/audio/reflect_a6.mp3"
};
export default audioMap;
